label ch2_main_a:
    $ _history_list = []

    with wipeleft_scene

    "As the sun rises slowly, filling the morning sky and basking the Earth in its light."
    "My sleepy self decided to turn and lay on my back. Eyes heavy with the need to sleep, I continued my slumber."
    "Feeling the comfort of my soft and fluffy bed, I almost missed that something was going on."
    u "Hehehe~"
    "A faint...{w}giggle? Am I hearing that correctly?"
    "I guess it's just my dreams playing with me. I mean if I can hear some weird slurping sounds right now then giggling was surely in my dreams."
    "Still trying to drift back to sleep, which isn't working; I suddenly feel a warm, wet sensation followed by some slick, slurping noises."
    u "slurp...{w} lick...{w} suck...{w} gulp..."
    "Huh?...{w} Wait a minute? This is somewhat familiar..."
    "I can remember this sensation like it was just yesterday. A soft, slippery and warm mixture of flesh and saliva."
    "I slowly opened my eyes to confirm what my body is feeling right now."
    "As the sleepy slowly goes away and vision starts to get clearer. I can clearly see that Seika, my little sister is performing something that my body longs for quite a while now."
    mc "Seika?"
    "I softly called out her name."
    s "Oh! Gohhd mohhnhn slurp...{w}"
    "Somewhat audible, Seika greets me a Good morning as she continue sucking off my cock early morning."
    mc "Seika... What are you doing?"
    s "slurp...{w}Ah~...{w} What do you mean what am I doing? I'm obviously giving you a morning service, my dear brother... hehehe~"
    mc "kugh... ahhh..."
    "I let out a faint moan as Seika continues to riddle my cock amounts of pleasure."
    s "Hehe~ I like that...{w}slurp...{w} lick..."
    s "Oh dear brother...slurp...slurp...lick...gulp... I love hearing you moan out of pleasure~"
    mc "Ahh~...Ughh...aghh..."
    "I can't control my moans as my body continue to enjoy my little siste's small mouth."
    s "That's it...slurp... Let me hear those pleasurable music...slurp...gulp..."
    s "I know that...slurp..you've been hoping to get...slurp...your cock again by...lick...your little sister~"
    s "Isn't that right...slurp...slurp...brother? hehehe~"
    mc "Ahh...hah...Seika...ugh...wait!"
    "Seika's movements suddenly goes rough as if she wants me to cum and release all of my load."
    mc "Seika...ahhh...ughh...hahhhh"
    s "Oh~ I like that bro~...slurp...slurp...slurp...gulp... Turn me on with those moans~"
    mc "Seika...gahh...hahh...hahhh...I'm...gonna...ahhh~"
    s "Oh~ Big bro can't...slurp...slurp...handle it anymore? hehehe...lick...lick...gulp...~"
    s "No need to hold back...slurp...slurp...slurp...~ Just let it out~ slurp...lick...lick...~"
    "Still continuing her rough and fast pacing. My body can't keep this up and I need to let out all of my pent up cum."
    "And without any form of hesitation, I let my carnal lust go wild and grabs Seika's head with both of my hands."
    s "Bro--hummmpppp...!"
    "I didn't wait for Seika to adjust and I proceeded on my ramming my swelling rock hard cock in and out of her small mouth."
    "Even with my cock, I didn't expect that it would reach and feel the back of Seika's throat. Not gonna lie, this feels good."
    s "HMMM!!! AHh~ gluhg! gugl! AhcK! HAh! HMMP! UHMP! GULP! SLURP! SLURP!"
    s "Bhhrrmmm! ahhh! Gahh! StAhhhhgggg!~"
    mc "Seika...ugh! Seikaaa...gahh!"
    mc "Seika....Seika.!...Aghhh!...SEIKAAAA!"
    s "HMM! AGh! Ghlug! GHuLG! UhAHh! HAHMPPP! SLURP! GULP! GULP!"
    "With all of my strength, I unleased all of cum inside Seika's small mouth down to her throat."
    s "HMMGGHH!...Gulp...! Gulp...! Ackh! Gag... Ahhhahhh...Hahhhh~"
    "As I continue to fill up Seika's mouth. She struggles to swallow everything at the same time, making sure that none of my cum spills out."
    "Right after my ejaculation, all the remaining strength of my body has been depleted. My body slowly falls down to the comfort bed."
    "Tired, I just gasp the air in and out of my lungs. Making sure that I am taking oxygen."
    mc "Seika...hahhh...Are you...Haahhh...alright?"
    s "cough! cough!"
    s "That was mean brother!...hmph!"
    "Seika cutely pouts as she was clearly angry about what just happened."
    s "What if your cum sprayed all over my school uniform. Ugh! The stain won't go off so easily, you know!"
    mc "I'm sorry about that Seika."
    "Her pouty attitude slowly shifted back to her other and much more calmer demeanor."
    s "So... How was it, big brother? Did it felt good? Hehe~"
    "Seika slowly crawls just about above my chest and rested her head there. I can still totally smell the shamposs that she used the other day."
    mc "It's not that I don't like it, but..."
    s "But?"
    "What am I saying or feeling right now, we shouldn't be doing something like this. Especially that you are my little sister."
    mc "I just can't..."
    s "What do you mean that you can't?"
    "Seika focus her eyes onto mine giving me a sharp gaze. I averted the direction of my eyesight somewhere else."
    mc "It's because you are my little sister. And I can't just do this to you."
    mc "It's not rig--{nw}"
    "Before I could even finish my sentence. Seika grabs my face and proceeds on kissing me."
    mc "Hhuph..."
    s "hmmm..chup!"
    s "I don't care if you are my brother or a complete stranger."
    s "I love you because you are there for me when I needed you the most."
    "And with that, Seika proceeds on hugging me and I return in favor."
    mc "Seika... As I said, this is something that we shouldn't do."
    mc "But, do remember that I'm always with you. Forever."
    s "Forever, really?"
    "Seika looks me directly with tears slowly falling down her face. I know that she needed someone she can depend on and trust."
    mc "Yeah, I promise Seika."
    "Seika sweetly smiles and buries her face on my chest. I once again pat her head to show that I really do care for her."

label ch2_main_b:

    with wipeleft_scene

    "Same as usua like any other day. Seika and I manage to complete our daily morning routines right on time before we leave the house."
    s "Big brother!"
    s "Looks like we are going to be late if we keep on stalling. We need to get going now."
    "And same as always, Seika pushes me to pick up the pace despite we are always early."
    mc "I know, I know, Seika. We are still early you know. Plus, I wanna go slow a little bit."
    "I moved near to Seika and whispered on her ear."
    mc "I'm still a bit tired on what we just did this morning."
    s "Eck!?"
    "Unable to express her expressions. Seika just blushes and shoves me away."
    s "Shut up! ARHG!"
    "I simply gave Seika the usual pat on head. As I looking around the neighborhood, I noticed that 2 familiar faces are running towards my house."
    a "Good morning, [player] and Seika!"
    i "Good morning everyone. Are you ready to go to school now?"
    "Alice and Iris both greeted us a good morning. From the looks of it, they want to go to school together."
    "Not that I mind, I really do prefer walking to school with a lot of company as I never had any close friends to begin with."
    mc "Good morning to the both of you as well. And yes, we just finished locking the house, we are basically ready to head to school now."
    s "..."
    "Seika rushes behind and used me as a wall to hide. She is clearly not warming up with these two."
    "I know that Seika is not fond about me being close to other girls and I know that Seika also a bit shy when it comes to talking to other people."
    "Maybe I just need to push her to befriend these two."
    mc "Come on Seika. No need to be shy and just say hello to them."
    s "..."
    "Slowly moving away from my back and step out of her shell. Seika started to head to the two girls."
    s "...Good morning..."
    a "Good morning, Seika. I really do hope that we could still get along like we used to."
    i "Oh! You were close before or have you met a long time ago?"
    "Iris curiously asked Alice."
    a "Ah yes! We've been neighbors for the about ten years now. We all went on the same school eversince we just kids."
    mc "Alice and I go way back. We used to play around everyday when we were kids."
    i "I see! That's really wonderful. I wish that I had something similar to that. I am quite a bit jealous actually."
    "Iris smiles as she show a lot of interest between our relationships."
    a "Why Iris? Didn't you have any childhood friends?"
    i "Well, I never had any friends growing up. I was always inside my house and my parents are very strict when it comes to people."
    i "Also, I was almost always sick when I was a kind. Most of the time, I spend my days inside the house to avoid anything that could trigger my sickness."
    "Iris goes about in sharing us about her simple childhood life and how she was mostly stuck in her own house."
    a "Wow...I am truly sorry about being insensitive regarding this topic. I'm truly sorry Iris."
    mc "Same for me. I didn't know that you have a really tough childhood."
    i "Oh no! That's actually fine, really! Nothing to be sorry about."
    "Iris jumps in and reassures that everything is alright regarding this specific topic."
    i "What's important here is that I can call you all three my close friends. Hehe~"
    a "I'll be more than glad to be your friend."
    i "Oh my! The pleasure is all mine."
    "The two girls smiles and laugh at each other. From the looks of it, they never really converse when they are still working under the same committee before."
    s "...uhm..."
    "The moment is suddenly interrupted by Seika as she steps in and interjects with the growing conversation."
    s "Can we go now? We might be running late with all the unnecessary chitschat."
    s "I don't mean to be rude by we might be late. Right, brother?"
    "Seika turns to me as if she wants someone to agree with her statement. As I cannot say no to her as she is clearly in the right in this case."
    a "Now that you have mentioned that Seika. You are right, we need to get going now. We'll continue with this conversation sometime soon, Okay?"
    i "I agree with the both of you. Let's all be off to school now, shall we?"
    "The situation was immediately diffused with the help of these two. They sure know how to handle these types of situations."
    mc "Alright, let's all go."
    "Seika, Alice, Iris and I walked together through our small neighborhood and to our school grounds."
    "Unlike the atmosphere from yesterday. The situation is much lighter as Alice and Iris are now talking to each other."
    "I wish that Seika could do the same. She's really not always in good terms with people I meet especially girls."

    with wipeleft_scene

    "As we are getting close to our destination, Alice slowly approached me."
    a "By the way, [player]. Are you able to complete all the documents that you took from me yesterday?"
    a "I would like to turn those all in first before I head to my class."
    mc "Oh yeah, don't worry. I have it right here on my bag. Let me just get it for you."
    "while walking together, I opened up my bag and grab the folder that contains all of Alice's documents and reports about the school fundings."
    mc "Here you go."
    a "Thank you so much for your help on this one."
    mc "No need to thank you me. Your original reports are all correct, I just did some minor changes but all of it are still originally your computations."
    mc "This means that you are doing a fantastic work already. You don't need to worry about making any mistakes."
    mc "And if you feel that you are in a pinch. Just don't ever hesitate to let me know as I'll be sure to help you out as soon as possible."
    "I smiled brightly at Alice. I just want to reassure her that she's doing a wonderful job already as the president of the student council."
    "Not only that, I want to let her know that she's always got a friend to help her out at all times."
    a "I really can't thank you enought for all of your hardword and encouranging words."
    a "And yes, I do need help from time to time. Please, if you are not busy after school. Do visit the student council room."
    mc "I'll be sure to visit you right after school, Alice. Don't worry."
    "Alice smiled as I promised that I will visit her right after school. With that, we continued on with our journey towards to school."

label ch2_main_c:

    with wipeleft_scene

    "As we all arrive to school, we then head to all of our respecive classrooms."
    "For third years like Iris, she has to stay in the first floor where all third year classes are being held there."
    "Alice and I head to the second floor as our classrooms are located there. She went ahead and checked with the Faculty Office meanwhile I head to my designated classroom."
    "And lastly, Seika heads to the third floor as their classes are being held on that floor."
    "On my classroom, I head straight to my assigned seat once again and the class starts right on time as always."

    with wipeleft_scene

    "After class"
    "Ding{w} Dong{w} Ding{w} Dong"
    t "Alright class, that's the lesson for today."
    t "If you have any extra activities, please do make sure that you return the keys back to the faculty office. The rest of the class, please be home safe. Dismissed."
    "I stretched out my arms as I let out a long sigh."
    mc "Finally! Classes are done for the day. My butt is already sore from sitting all day."
    "Checking on the classroom clock, I have noticed that I have a lot of time to help all the girls today."
    mc "Hmm... Maybe I should check out Alice since she's the nearest from here."
    "I immediately pack up all of my stuff inside my bag and proceed on going to the student council room."

    with wipeleft_scene

    "Walking through the corridor, I made my way right by the student council room's front door. And from here, I can tell that the scene is hectic as usual."
    "I gently slide the door open and I greeted everyone inside the room."

    with wipeleft_scene

    mc "Good Afternoon!"
    vp "Oh! Good afternoon, [player]!"
    sc "Yes, a very pleasant afternoon to you as well, [player]."
    "The two officers casually greeted me as they both frantically walking around the room."
    mc "Another hectic day, huh?"
    a "Hi there, [player]. Yeah, we are still completing all the documentation before we could arrange the budget for the school's cultural festival."
    mc "I see that, anything that I can help with? I did promise that I'll help you around here."
    a "Thank you, [player]."
    "Alice stood up from where she was sittng and walks outside the council room to the corridor. Signaling me to follow her."
    a "Please come with me. I need some help printing some documents. I just want to make sure that I don't overlook at thing again."
    a "Vice President and Secretary, I'll be taking [player] for a while. Please do continue your hardword. We'll document all the final budget check once we are back."
    vp "Sure thing, Prez. You can count on us!"
    "With that, Alice left the student council room and I shortly follow."

    with wipeleft_scene

    "As we are about a good distance away from the student council room, Alice's mood change and let out a long sigh."
    a "Can this day just be a little be gentle with me?"
    mc "Anything wrong Alice?"
    "I asked her a question just to try to ge the whole story regarding her stress."
    "But, Alice just let out another long sigh clearly showing her stress about this topic."
    a "It's just all the responsibilities I currently have right now. Home, school, and student council. Everything is just too hard to keep track of everything."
    a "This is why I wanted you to follow me so that I don't really overlook at things again. I tend to forget minor details just to stress for some strange reasons."
    mc "I see that, we'll don't you worry. I'll be sure to help you out with any ways I can."
    a "Thank you, [player]. You really are kind."
    "Out of the blue, Alice just said a compliment that I didn't expect which caught me off guard."
    mc "Uhm...Thanks, Alice. I never really get any compliments from anyone else aside Seika. That really means a lot to me."
    "I smile as I look a Alice's face."
    "And right before we knew it, we manage to arrive at the printing and copy maching room."
    a "Well, here we are."
    mc "I actually never been in this place before."
    a "Oh! That is actually normal because this room is only for faculty and student council use only."
    a "We want to make sure that this machine doesn't get overused as it is expensive to buy a new one."
    mc "Oh I see now. It's basically an exclusive use only kind of thing?"
    a "If you put it that way. Yes, it does sounds something like that. Hehehe~"
    "I never knew that a photocopier machine exist inside this school. The more you know I guess?"
    mc "Shall we head on inside?"
    a "About that..."
    mc "Hmm?"
    "Alice stopped me right when I'm about to reach the door's handle."
    mc "Something the matter, Alice?"
    a "Normally, I would suggest that you wait for me outside the room as it is really cramped inside."
    a "But this is an exception as I would like to be sure that I'm actually doing my work correctly."
    mc "I guess that we could fit inside the room."
    mc "Don't worry, I will squeeze out if you need a lot of space to work with."
    "I assure Alice to make sure that everything will go well."
    "Alice then proceeds on opening the door and I cannot believe my eyes."
    mc "This room..."
    "I'm not going to even sugar coar what I'm seeing but this is totally something that we both cannot fit."
    a "Yeah...{w}I'm sorry about all of this."
    mc "Uhh...Alice..."
    mc "Correct me if I'm wrong but is this the old janitor's closet?"
    "The printing and stock room is actually nothing more but the old janitor's locker."
    "This used to be a stock room for cleaning materials such as brooms, mops, and detergents."
    "I am both amazed and confused how did the faculty or student council manage to fit the printer machine on this tight space."
    a "Uhh...Yes, you are correct."
    a "This was the old janitor's closet before they completely store all of their equipment behind the gym lockers."
    mc "I can see that. But still, we might have a hard time fitting inside here."
    a "Well, we can only try."
    "Alice held my hand and she went inside the closet bringing me along with her."
    mc "Wait! Alice! I think that we shou--"
    "Right before I can finish my sentence, Alice and I ended up tripping on the door frame."

    scene black with vpunch

    "*crash*" #sfx

    "As we both fell on the ground, the door behind us closes."
    mc "Ugh...Alice...Are you okay?"
    a "Uhh..oww...That hurts..."
    mc "Argh...I'm really sorry Alice, are you hurt somewhere?"
    "As we forgot to turn on the lights, the closet is very day and we cannot see each other."
    "And as I try to move my hand, it touches something that is very smooth and soft."
    a "EEEP!"
    mc "Huh? What's this?"
    a "Ah~...[player]...That's my..."
    "As my mind slowly comprehend what I'm touching. Soon I realized that I was actually touching Alice's sides."
    mc "I AM SO SORRY ALICE!"
    "I quickly stood up and leaving Alice still laying on the floor."
    mc "That was very rude of me, I am truly sorry Alice."
    a "It's fine, [player]. I really don't mind it as long it's just you."
    "Even though that it is dark inside the clothes, I was able to see the silhoutte of Alice as she tries to sit down rather laying down."
    mc "Hang on Alice, let me just find the light switch real quick. Okay?"
    a "WAIT [player!u]!"
    "Right before Alice finished her warning, I was able to turn on the lights."
    "And the next thing that caught my eye is that Alice's clothes are lifted and I can see her slender body perfectly."
    a "EEEK! DON'T LOOK!" with vpunch
    "Quickly covers her exposed skin using her arms. However, it was already took late as the image is already burned into my memory."
    a "{i}This is embarassing...{/i}"
    "I heard Alice whisper but wasn't sure what she actually said as I was still frozen in place to see her figure."
    "After a few brief moments, I was able to snap back to reality."
    mc "I-I...I have no excuse huh?"
    "Alice didn't reply as she continues to lower her head and still covering up her body with only her arms."
    "Her face is already red crimson and I can still see a bit of her skin."
    a "[player]..."
    "Alice break the tense silence."
    mc "Alice... I swear to God I am really sorry for what just happened."
    "Alice shook her head."
    a "It's not that..."
    a "I'm just...{w}embarrassed you see..."
    a "My body isn't that great and all..."
    mc "What are you talking about? Your body is obviously se-- I mean beautiful!"
    "I protested as I compliment Alice's beautiful and curvacious body."
    a "...Then..."
    "Alice stoods up."
    a "What do you think of it now?..."
    "Alice slowly removes her top and i wasn't prepared for what I'm about to see next."
    mc "ALICE WAIT! YOU SHOULDN'T!" with vpunch
    "As Alice slowly reveals her body to me, I finally got a good look of what she is hiding under her daily life."
    "Aroung Alice's chest, shoulders, stomach and sides. It has bruises and markings. Clearly a sign of someone that was beaten or abused."
    mc "Alice...Is that..."
    a "..."
    "Alice was quiet while I slowly grasp the situation."
    "I cannot understand nor comprehend what I'm actually seeing right now."
    "My childhood friend, a close friend covered in bruises. Hidden in plain view."
    mc "...Why?"
    a "There are some things that you don't need to actually know..."
    a "And if you are wondering. Yes, I am perfectly fine with it."
    "Alice coldly replies as she wears her top clothes once again. Meanwhile, I'm in total shock. I don't know what to say to begin with."
    "I'm just there, frozen and cannot comprehend the situation presented to me right now."
    mc "Alice...What is the story behind those marks?"
    "I mustered up my courage just to speak those words as I cannot look Alice straight in the eyes."
    a "[player]...I already told you. It's something that you don't need to know about."
    mc "DON'T LIE TO ME!" with vpunch
    "I yelled at Alice as I know she's already on the point of breaking and no being able to recover."
    mc "I know that you are sufferring. And I know that you needed someone that you can trust to open all of these up."
    mc "And now, you won't even tell me the truth right now?"
    mc "I may be dense but I'm not that blind. You are my good friend and I care a lot about you."
    "I fiercely gazed on Alice letting her know that as her friend I do care for her well-being."
    a "*sobs*"
    "Alice's tears slowly trickle down her face. And I slowly approached her."
    mc "Alice..."
    "I grab a hold of Alice and I gave her a warm embrace to reassure her that I'm always with her."
    mc "You don't have to fight alone, I'm here. You can trust me, right?"
    "I can feel Alice's arms and hand slowly crawling on my back as she returns the favor. Giving me a tight embrace."
    a "I'm scared...I'm really scared, [player]!"
    a "I don't want to feel this ever again!"
    mc "I know Alice... Know that I am here, always by your side."
    a "WAHHHHHHHHHHHHHHH!!!"
    a "[player!u] I DON'T KNOW ANYMORE! I REALLY DON'T KNOW ANYMORE! I JUST WANT A NORMAL LIFE!"
    "Alice continues to cry her heart's out. It was a good and secluded place to let out all of her emotion and pent up sadness."
    "The room is really far from any classrooms and most of the students are mostly gone or doing their extra activities."
    "I still wonder...What is the story behind those bruises?"
    "It doesn't look like the normal bruises you get from getting beaten. This is way different and yet, I decided not to pry on the matter. There is a perfect time for Alice to open up."

    with wipeleft_scene

    "After a few good moments, Alice finally starts to calm down."
    a "*sniffs*...[player]...I'm sorry for always crying in your arms."
    mc "It's fine Alice, I'll be youtr crying shoulder every time you need it."
    "Alice breaks away from the embrace and tidied up herself up."
    mc "We should start doing what we should've done earlier."
    a "Yes, I agree on that note. That way, we'll be able to go back to the studen council room."
    mc "Alright, let me handle the rest. Why don't you open the door. It'll be bad if someone saw us go out at the same time."
    a "Okay, let me just open the door."
    "Alice slowly open the door and I started to boot the printing machine. Gladly that no one is around when Alice opens the door. We just avoided a possible school scandal."
    a "Alright, looks like there is no one around. How are you over there?"
    "Alice turns to me as I print all the documents needed for the budget logs."
    mc "I'm about to be done, don't worry. Just give me a few minutes."
    a "Okay then, take your time."
    "I manage to take care of all the documents and store them on a folder binder."
    mc "Looks like everything is printed and documented. What do you think Alice?"
    a "Yes, it's all in order. Thank you for your help."
    mc "It was nothing Alice."
    "Alice smiles warmly as I hand over the documents to her."
    a "I guess I'll be going back to the student council room then. What are you going to do now?"
    mc "I guess I'll be helping Seika with her club now. I did promise her to help her out."
    a "I see, then I better get going then. I'll see you later."
    mc "Yeah, I'll see you later."
    "Alice walks away carrying the documents. Looking at her from a distance, it feels like all that happened earlier was just a bad dream."
    "But it wasn't, it was all true. And I didn't even manage to know anything about it."
    "I just hope that one day, Alice will trust me enough to help her get her through her struggles."

    with wipeleft_scene

label ch2_main_d:

    "After helping out Alice with her student council duties, I went down the staircase and head directly to Seika's softball club."
    "it's really is pain just to walk to the back of the school just to visit the shed which we call now a clubroom."
    "As I reach the outside of the clubroom, I noticed that the door is already wide open."
    "Considering the classes ended up a while, it would make sense if Seika and the other members are already here."
    "As I went inside the clubroom, I saw the lone Seika scribbling notes on the board."

    with wipeleft_scene

    "To get her attention, I sneak up on her..."
    mc "Whatcha doin?"
    s "Eek!" with vpunch
    "Seika startle and she manages to break the chalk in the process."
    mc "Hahaha! That's a cute reaction, Seika."
    s "Uuu...Brother, you meanie! You know I'm easily startled."
    mc "I know, that's why I love teasing you."
    "Seika and I laughed it all out and put down my bag on one of the vacant stools."
    mc "By the way, where are the new members you have mentioned from your text before?"
    s "Oh! They're just getting some snacks. It's kinda boring here without any thing to do aside talk about softball. you know."
    mc "I see, we'll I'm just stopping by to get some snacks then."
    s "Oh? But you have to pay for those as they are collaborative funding."
    "Seika smiles pretty smugly. I can really see that she is having fun and enjoying her time with the new softball club."
    "It's been a while since I last saw her this passionate and happy about something she loves."
    mc "Oh! Before I almost forgot. Seika, turnaround for me, will you?"
    s "Eh? Why all of a sudden though?"
    mc "Just trust me on this one."
    s "Sigh...Fine...Just don't do anything stupid or I'll kick your shins."
    "Seika turns around and making sure that she doesn't take a peek. I slowly grab the fixed pendant inside my bag and unlocked the latches."
    mc "Close your eyes and no peeking, Seika. If you open up your eyes, I will take away your snack privileges for a week."
    s "GASP! You fiend! Hehehe. Alright, alright. You'te such a tease~"
    "Seika closes her eyes and I can feel that she's a bit giggidy and in a happy mood right now."
    "I slowly put the necklace on Seika's neck and lock it in place."
    mc "There! You can open your eyes now."
    "Seika opens up her eyes and she finally noticed her favorite pendant is back where it belongs."
    s "Brother, is this?"
    mc "Yep! I managed to fixed it last night without any problems. Although it is a bit shorter now compare before as I have to compensate for the broken chain links."
    "Seika turns around towards me and gave me a sudden pounce hug."
    s "Brother! I love you! Thank you so much for fixing it for me. Now I have nothing to worry about anything now!"
    mc "What is that? Some kind of a charm that you can't live without?"
    s "Hehe~ Something like that~"
    mc "Alright, since that's all done. What's our next plan for the club now, Miss President?"
    s "Geez, that's embarassing when you say it like that."
    "Without us noticing, the four new members entered the room. Along with the promised snacks."
    m1 "Yo Prez! We got the goods you asked for!"
    m2 "Oh Prez? Is this your big brother that you are always talking about?"
    m3 "Are you guys about to discuss our plans?"
    m4 "I just wanna eat some snacks first before we get started."
    "I see that my sister has recruited 4 of her friends and classmates. Not to mention, all of them are girls. That makes sense because this is a Women's Softball club."
    mc "Hi there everyone! Thank you so much for joining in our Softball Club. My name is [player] and I'm Seika's brother. I hope that you continue supporting my sister and her dreams."
    "I introduced myself to all of the girls and they set all of their snacks on the table."
    s "Alright! Since we are all here now. It's time to discuss our future plans with the Softball club!"
    "Everyone gathered their chairs on the front. Everyone is focued and I cas see tha this is already going to be a successful club."
    s "Our agenda for today is going to be recruiting the remaining members of the club."
    s "As of right now, we currently have five players and sixth member is my brother which is the acting manager of this club."
    "Did she just passed the leadership to me?"
    s "In order for us to fully compete in any games, we need to have the standard nine member players."
    "As I listen to Seika as she goes about her plans about her club, I cannot help it but to feel proud of her. She's slowly going out of her shell and leading these people with a single goal in mind."
    "The other day, she's saying that she almost regret being the self-appointed president of the club."
    "And now, look at her. She's not just a president of some club. She's also leading these people with great confidence."
    s "What I have in mind is that we will use the coming Cultural Festival to gather more memnbers."
    s "Showcasing our talent with our fellow freshmen, we'll be sure to get their attention and join our dream in competing in the championships."
    m2 "I totally agree with you Prez. This is our chance to make our highschool life the greatest!"
    amem "YEAH!" with vpunch
    "I can really feel the passion of these lovely individuals. I am very confident that they'll be able to pull this off."
    mc "Alright you guys. I can toatlly see the passion on each of everyone that is here right now."
    mc "And since we are all planning to get new members with the help of the festival. We would need a gimmick that can attract them here."
    s "Great idea, bro! A gimmick, huh?"
    "Everyone became quiet all of a sudden and all of them started to think for the best plan for this situation."
    m4 "Hmm... We could lure them in with snacks?"
    mc "Rejected, we are not a snackbar. Anything else?"
    m3 "We, we could lecture them about softball."
    mc "That is actually a great idea. However, this could lead them not being interested if we focus on lectures."
    m2 "I know! We could let them use our equipment have them try some basic swings on field. Like a batting cages."
    mc "Perfect! I like that idea! That will give them the opportunity to actually learn the game works. This could fit together with the lecture idea."
    s "How about we add a small demonstration to top it all ofF? I mean, if they saw us play the game. They'll get a better understanding of what's our club all about."
    "That's my Seika, alright. She's starting to become a great leader and showing all possible outcomes of their suggestions."
    mc "I agree with that Seika. Combining all the idea suggested. This is the perfect formula on getting more club members."
    s "Alright! That's settles up everything!"
    mc "Not quite yet, Seika."
    "I stopped Seika before she could celebrate."
    s "Why brother? Everything is already set in place, all we need to do now is prepare for the festival."
    mc "Yes, I know that. However, you are forgetting one more thing."
    s "What is it?"
    "Seika is completely clueless and confused to what is the thing the club is currently lacking aside the number of people."
    mc "You don't have a funding yet."
    amem "*GASP!*" with vpunch
    mc "You forgot the most important of all thing before this show goes on the road."
    mc "You need proper funding for this event. Gathering supplies and equipment are the number priority you guys need to focus."
    s "That didn't cross my mind to be honest."
    m1 "Me as well, I always thought that the school's budget will handle most of these expenses."
    mc "That is somewhat true. Allow me to go further into details."
    mc "If the club or club members need equipment or materials for their club. They can request a budget from the faculty and or student council."
    mc "After that, they will evaluate if these equipments are necessary for the club's growth. From there, they will either approve or reject your application."
    mc "This is where you will have to improvise on getting the necessary funding for the club. Since we cannot conduct any solicitations nor ask our parents for money."
    mc "We need to get part time jobs in order to supply the demand of our club."
    s "I see..."
    "Seika comically lowers her head as if she feels defeated."
    m4 "Prez! Hang in there!"
    s "Ugh... Real worls is such a pain..."
    s "But no matter, we are the Softball team and we will not be defeated in life!"
    "Seika triumphantly shouts and all of her followers followed her example."
    amem "YEAH!" with vpunch
    "She's really growing up and I'm so proud to see her like that."
    s "Alright you guys! Time for us to find a part time job!"
    m2 "Prez! How about we all work on that cafe shop?"
    m4 "Oh yeah! Remember guys they are currently hiring part timers and they don't have that much a customer."
    m1 "I agree on that one. What do you think Prez?"
    s "Yeah, that's the best idea we got so far. You guys wanna go now?"
    amem "Yeah!"
    s "Alright, that's all settled. Today's meeting is now adstained."
    mc "Adjourned..."
    s "I mean, Adjourned! Hehehe~"

    with wipeleft_scene

    "And with that, Seika concluded the club's meeting for the day. We then start packing all of our stuff and rearrange the room to be near. And we then head outside."
    "Seika then locks the clubroom and hand me the key."
    s "Can you return the key back to the faculty office. We'll be heading to the cafe right now so we can make it before night."
    mc "Alright, I'll just return this key to the office and head home afterwards."
    s "Okay bro, sorry I can't walk with you home today. I'm off then! I'll see you later at home!"
    "Seika waves her hand good-bye and she's accompanied by her friends as they exit the school grounds."
    "I have to say it one more time, I am proud of what she is right now. And I hope for the best of her future endeavors as the president of the softball club."

label ch2_main_e:

    with wipeleft_scene

    "Right after sening Seika and her friends off, I immediately went ahead behind the school garden to check on Iris."
    "However, as soon as I arrived to the garden, I have noticed that Iris is currently nowhere to be seen here."
    mc "That's weird, I thought that she'd be here today?"
    mc "Iris? Are you here?"
    "As I called out her name, I didn't get any single response."
    mc "Hmm... Maybe she went home early?"
    "As I'm about to leave the garden, I noticed that there is a note sticking on one of the pots."
    mc "A note? Maybe this was left behind by Iris."
    "Upon checking the note, it is clearly written by Iris and it is directed to me."
    "'[Player] Please do go to the roof top garden. I'll be waiting for you. - Iris.'"
    mc "I see, she's on the rooftop garden today. I bettery hurry up or else she'll keep on waiting for nothing."

    with wipeleft_scene

    "I immediately went inside the school building and went to the faculty office to return the club room keys before I forget them."
    "And without taking any breaks, I sprinted up to the roof top and opened the door seperating the school and Iris's Eden."

    with wipeleft_scene

    "And upon exiting, I noticed that Iris is already started tending her garden."
    i "Oh, hi there [player]. I've been expecting you. Did you noticed the note that I left for you on the other garden?"
    mc "Yeah, I noticed it before I went here. I almost thought that you went home already."
    "I then placed my bag near the shed and removed my jacket."
    mc "So, what assistance do you need today?"
    i "Oh, I just need a little bit of help removing some of the weeds grouwing on my garden. I just hate it when the weeds started growing and preventing my plants from growing properly."
    mc "Simple enough, I'll get it done immediately."
    i "Oh, before you start. I already prepared your gloves. It's there by the shed."
    "Iris pointed me where the gloces are located and I put them on. The gloves are those standard gardening gloves, but this one feels alittle but different. As if it's practically brand new."
    mc "Uhm, Iris. Just a quick question."
    i "Hmm? Yes, what is it?"
    mc "Are these gloves brand new? You know I could just use some of your old gloves."
    i "No need to worry, [player]. I bought those gloves specifically just for you. Since you'll be helping me with the garden, it would be best if you have your own protective equipment."
    "Iris smiles as she still continues tending her garden."
    mc "I see, thank you for this Iris. I'll be sure to help you lots with your garden."
    "Without wasting any further time, I quickly slide on the gloves to my hands and immediately started clearing out the weebs on the garden."

    with wipeleft_scene

    "Just like the same as last time, there's an awkward silence between Iris and me while we work together. I know that she's really into gardening and usually her thoughts floats away."
    "However, I would like to know more about her."
    "As I look at her from my side, I see her beautifyl face. Her hair and even the very glasses she wears. I can't help it but think that she's really a beautiful person."
    "As I continue staring at her, Iris slowly noticed that I've been looking at here for the past minute."
    "Her eyes made contact with mine and she immediately averted ir right before I can react properly."
    "Iris face slowly became a hint of red and look at me once again."
    i "Uhm...[player]? Is there something on my face? You've been staring at me quite intently."
    mc "Oh! I'm sorry, Iris. It's just was captivated by your beauty that's all."
    "Iris averted her eyes once again and her already red cheeks slowly crawling on her ears."
    i "[player], may you not use such flattery words as I cannot contain myself for being like this."
    mc "I'm sorry Iris. But that's the truth, you look really cute to be honest."
    "Unable to response back, Iris continue on working on her part of the garden with a beet red face."
    mc "Well, time to continue tending this garden. Sun is about to go down anyways."
    "I gazed on the sun slowly setting and turning the once bright day into a shade of orange."
    i "It's actually beautiful and sad, huh?"
    "Out of the corner of my eyes, Iris stood up and commented on the sun slowly setting."
    i "The color of the sun is slowly fading and replacing the world with darkness temporarily. It's like, how I view to world."
    i "I used to be a bright sun"
    i "And now, I am but a dark sky."
    "Iris sadly smiles as she bathe herself with the last remaining sunlight before the sun completely sets."
    mc "You may think it that way, but you said it yourself. Darkness is temporary, the sun will rise again tomorrow."
    mc "You don't have to worry about a thing and just do your best."
    i "I guess, I think that you are right on that one."
    "Iris took a deep breath like she's inhaling a good fresh air for one last time."
    i "I guess we should wrap things up for now, and besides it's already getting a bit late."
    mc "Okay, let me clean up everything so you don't have to worry about a thing."
    "I took the trowel from Iris's hands and I put everything back on the shed where everything belongs."
    "Iris then prepares all of our stuff and packed her school bag neatly. I did the same afterwards."
    "As we are about to leave the roof top, I thought that it would be the best if I accompany Iris back to her house."
    "It's already getting late and it's dangerous to walk alone. Also, I want to get to know her more while walking home."
    mc "Hey Iris, do you wanna walk home together?"
    i "Oh [player], I was just about to ask you the same thing."
    "I'm actually surprise to know that Iris wants me to go walk with her home."
    i "it's about to be dark and my eyesight is not always been the best, can you assist me on going home just for the day?"
    mc "I see, if that is the case. Let me carry your bag, this way you'll be able to walk wihout carring any weight."
    "Iris hands me her school bag and I slide it on my shoulder."
    "We then proceed on leaving the school's premises and proceed on waling towards our neighborhood."

label ch2_main_f:

    with wipeleft_scene

    "As Iris and I leave the school grounds, I make sure that Iris is safe as she is showing some struggles wlaking under minimum lighting."
    mc "Are you sure that you are okay, Iris? Looks like your about to stumble any moment."
    i "I'm perfect fine, [player]. It's just already dark and since I'm nearsighted. This is to be expected, so nothing to worry about."
    "Iris smiles as shes struggle to look at my face directly, more like she can't find my face."
    mc "Well...here, grab hold on my arm. This way we'll be able to walk together and catch you if you ever fall down."
    "Despute the literal darkness of the streets. I can still see the cute beet red face of Iris once again."
    i "I have to decline on that offer, [player].{w} And besides, I can st--{nw}"
    "As right before Iris can finish her sentence. She suddenly trips on a uneven surface of the road. Causing her to fall down."
    "Luckily, I was able to catch her right away. Saving her from the fall."
    mc "Iris are you okay? Are you hurt somewhere?"
    i "I-I-I'm perfectly fine, [player]. Thank you so much."
    i "I guess I really do need new prescription glasses... sigh..."
    i "I really don't like wearing glasses. It really hinders my view and sometimes it gets in the way of my daily routine."
    mc "What are you talking about Iris?"
    "Iris looks at me completely puzzled about what I just said."
    mc "You look way more attractive with your glasses on."
    "Once again, I caught Iris off guard. She blushes making her already red face more redder."
    i "You must you tease me this way, [player]?"
    i "It's not that I don't like it but, sometimes I can't hold it in."
    "Iris let out a small sigh."
    mc "I'm sorry Iris if you feel that way. Don't worry, I'll stop teasing you."
    i "Please don't stop!"
    i "I mean, it really doesn't bother me or anything. And if it's just you, I surely do not mind."
    "Iris smiles sweetly as she insist that I won't change my habit around her."
    mc "Alright, I guess that's fine. Should we continue moving along? It's getting really dark already."
    i "Yes, we should get going now."
    "As we continue to walk together, Iris grabs hold on my right arm."
    i "..."
    "Iris is quiet and continues to cling on my arm."
    i "You told me that I can hold your arm until I can get home."
    mc "Well...yeah. But I didn't expect that you'll actually do it. I'm actually a bit embarassed now as well."
    "We both averted our eyes at each other as the awkward scenario kicks in."
    mc "..."
    i "..."
    "As we stood still on a dimly lit street almost near our neighborhood, all of sudden a drop of rain slowly falls from the skies above."
    i "Oh no! I didn't brought any umbrella with me today."
    mc "Ugh... Same... Come on, Iris! There's a shed over there, let take cover from there for the time being."
    "I immediately grab Iris's hand and I carefully guide her towards the simple bus stop shed."

    with wipeleft_scene

    "As the small drop of rains slowly turns torrential. Iris and I cannot do anything, but to stay in the protection of the small shed. And we hope that the rain light up soon or we have no choice but to make a run for it."

    scene black with dissolve

    "A few moments later..."

    with wipeleft_scene

    "As the rain continues to fall, we have noticed that it's already getting late and most of our stuff are drenched in water."
    i "Oh no... My clothes are all wet. My skirt is dripping as well..."
    "Iris complain as she tries to wriggle the water out of clothes. I did the same with my jacket as it is completely drench from the rain."
    i "I just hope that my plant back in school don't get too flooded."
    mc "Yeah, it would be a shame if that ever happens."
    i "Well, this is better, I guess?"
    "Iris starred up to the heaven from the stop, looking ahead."
    i "Plant rejoice when the skies cries out. Without their cries, they would wither down and die."
    "Then Iris goes back to me and look through me directly to my sould with a pathetic smile on her face."
    i "Just like the world wants me to cry for them to survive."
    "I cannot understanding at this point whether Iris is crying or is it just the water coming from the raindrops."
    "But one this is for sure is that a terrible way of saying your life is nothing more but an amusment to others."
    mc "Iris...that's just..."
    i "I'm just pathetic, right?"
    "The rain conitnues to grow stronge as well as the emotions surround us became unsettling."
    mc "Iris, you are not pathetic. You are what you think you are."
    i "That's whay I always think..."
    i "But that's not what my demons are thinking."
    mc "You don't have to listen to your demons to decide what you are Iris. All you have to do is slowly get better."
    "What am I talking about? I don't how to help her. This is something she needs professional help with."
    i "I know that [player]. I'm always aware what is the difference between my voice and the sounds of their voices."
    i "It's just hard to control them but I do make sure that I stay composed."
    mc "I understand that Iris, but if you ever need someone to comfort you. I'm herer, I'll be more than happy to listen."
    "iris didn't say any word and completely starred at the rain as it continues to fall down. I can't do much do here for her. All I can do is support her."
    "As the rain continues to grow stronger and showing no signs of stopping. I can't help but think, we are going to be here for a long while."
    "I checked on my phone to see if I could ring Seika's phone to help us get an umbrella."
    "But alas, my phone is already dead."
    mc "Damn it... My phone is dead. How about you Iris? can you contact someone to get us an umbrella?"
    i "I'm sorry [player]. But my phone just died as well."
    mc "I guess we are stuck here for the time being huh...sigh..."
    i "Hmm... Hey uhm...[player]."
    i "How fast are you?"
    "I looked at Iris as she asked me a very strange question on this situation."
    mc "Well... I'm a bit fast but why ask so suddenyly, Iris?"
    "Iris smirks"
    i "Well..."
    i "Take this!"
    i "TAG YOU'RE IT!" with vpunch
    "Iris suddenly taps on the shoulder as she bolted out of the covers of the bus stop."
    i "Ahaha~"
    mc "Iris! Wait! It's raining and you're going to get wet!"
    "Iris completely ignored my warning as she taps aroung the small puddle of waters."
    i "I don't care! We're already drenched anyways, might as well play in the rain! Ahaha~"
    "Comepletely different from the Iris from earlier, this one is smiling sweetly as if she doesn't have any care in the world."
    "Giving in, I decided to follow her lead. Together, we ran like hell while enjoying the rain falling down from the skies."

    with wipeleft_scene

    "It didn't take that long as we are able to reach the front door of Iris's house."
    "We made if safely without slipping. The only price that we have to pay is that all of our clothes and belongings are completely drenched."
    i "Here we are, we made it~"
    mc "huff...puff...huff..puff..."
    "I can't believe that Iris isn't even tired after running that fast. Meanwhile, I'm planting like a pig."
    mc "I never taught that you were that fast in running and here I thought you are going to slip or even trip."
    i "Hehehe~ I love playing tag when I was a kid."
    mc "That's make sense."
    "Iris then opens the door of her house. Oddly enough, it seems that one is home as it is completely dark inside."
    "And since I only live a couple block furhter, I decided to leave Iris."
    mc "Well then, I guess I'll be seeing you around Iris."
    "As I turn around, Iris grabs hold of my hand as if she doesn't want me to leave yet."
    mc "What is it, Iris?"
    i "Uhm...Your clothes...They're all wet. You can use my laundry machine to clean and try your clothes."
    i "Also, it is still raining. You'll be drenched again."
    "iris seems a bit persistent and I don't know why. But since she's all alone, I think she just want some compnay."
    mc "Hmm...Alright, I might as well warm up here for a bit while the rain lighten up and my clothes dry."
    "Iris's eyes lighten and perked up as she smiles very sweetly back at me."
    i "Right...Well...Follow me inside, I'lll prepare you some spare clothes."

label ch2_main_g:

    with wipeleft_scene

    "As iris leads me to the laundry room, she went on ahead and goes to the second floor to prepare a spare clothes just for me."
    "I took off all of my drenched clothes and put them on the machine and set it to regular wash."
    mc "sigh...I never thoughtt that I'll be washing my clothes on a woman's house. This is embarassing..."
    "I contemplate my life choices as I let out a long sigh. Nothing that I can do now, I just hope that the rain ligthen up and my clothes dries fast."
    "I turned the maching on and the whirling sounds reverb from the machine."
    i "[player]? Are you okay in there? I brought you some clothes."
    "Iris's feint voice can barely penetrate the barrier of the door."
    mc "Iris? Yeah, I'm okay in here. I just started the machine not long ago."
    i "I see...Well, I'll be leaving your clothes here by the door. I shall take my leave for a while."
    "I heard Iris trots away. From where I am, the sounds of her footsteps slowly fades to the distance."
    "As I know the cost is clear, I gently opened the door to grab the clothes that Iris has left for me."
    "I slipped on the clothes that Iris's lent to me. On first glance, I really thought that the clothes would be too big or too mall for me."
    "Oddly enough, they just fit too perfectly."
    mc "These clothes looks fairly new; I wonder if this her father's or brother's clothes."
    mc "Well, I better just leave this machine to clean and dry my clothes."
    "And with that, I left the laundry room and head to where Iris is at."

    with wipeleft_scene

    "As I leave the laundry room, Iris immediately greeted me."
    i "Oh! Hi there, [player]. Do the clothes fit you well?"
    mc "Yeah, it fits pefectly. It this your brother's clothes?"
    i "I don't have a brother though, but I do wished that I had one."
    mc "Oh, so it's your father's then."
    i "Anyway, [player]. Care to join me by the couch? It's going to take a while before the rain lightens up and fot your clothes to dry."
    mc "Okay then, sure thing."

    with wipeleft_scene

    "A few moments later..."
    "..."
    "It's been a good while since we started with this awkward situation. Also, there is no sign of the rain lightening up. We are really stuck in this situation."
    "As my thought sway further, I didn't realized that Iris is just an ich away from my face and calling out to me."
    i "[player]? Are you okay? You looked like you are spacing out."
    "To my surprise, i started to startle and so does she."

    scene black

    b2 "WAAH!" with vpunch
    "A startle Iris accidentally pull me closer as she slowly falls down of her back."
    "Luckily, the sofa was soft enough to cushion her fall. Meanwhile I ended up falling face first on her chest."
    i "[player], are you okay?"
    mc "Yeah...I think I'm okay, Iris"
    i "KYAA!" with vpunch
    "A cute squeel resonate and reverberate around the living room."
    "Without me noticing, I was actually groping Iris' left chest."
    mc "WAH!"
    "I immediately released iris and went back to my side of the sofa. Embarassed, I faced the other way. Making sure that my reddish face is away from Iris."
    "Crap... I didn't really that I would immediately escalate to that. But holy crap... It feels really soft despite the size."
    i "...Uhm...{w}[player]?"
    "Still facing away from Iris, I couldn't tell if she's mad at me or also embarassed what just happened."
    i "...uhm...{w}[player]? I wanted to tell you something..."
    i "But sometimes... I cannot say it because I'm too embarassed and or scared."
    mc "I-I see...{w}What is it then, Iris?"
    "Without any warning, Iris grabs hold on the collar of my shift and pull me towards her."
    "As our face is nearly just inches away from each outher. Iris ducks her head to hide her flustered face."
    "I averted my eyes to the right as I am also embarassed as to what is actually is happening in our situation."
    i "You know, [player]. I don't know about this... but..."
    i "My heart can't seem to rest when I'm around or near you."
    mc "Iris..."
    i "The trust is that..."
    i "I think I have feelings for you!"
    "As Iris admitted her true feelings for me, our world suddently stopped."
    "I cannot believe what I've just hear from Iris's lips. I'm somewhat thankful at the same...this is not completely right..."
    "There is a fine line between helping a friend with her depression and becoming her lover..."
    mc "Iris...{w}wait... Since when?"
    i "It all started because of my depression..."

    with wipeleft_scene

    "This was when I was still living in a different neighborhood..."
    "One night, I was walking late as my Student Council duty took all of the right after my class ends."
    i "{i}Sigh...That took a lot of time than I have expected. I didn't even had any time to to tend my plants.{/i}"
    "And since I am near sighted, I can't clearly see at night or you could say that I'm partially blind during the dark nights."
    i "That's when"
    u "{i}Hey you! Give me your wallet!{/i}"
    i "{i}?!{/i}" with vpunch
    "Out of nowhere, a man that I can't picture his face emerged from the shadows pointing a knife and demanding me to surrender my wallet."
    "At that time, I was very scared as I cannot fully see and grasp the situation properly."
    i "{i}'W-w-w-w-what am i going to do?! I can't see him properly! I don't know if there is someone nearby'{/i}"
    "I didn't know what to do as I'm just frozen in place."
    u "{i}HEY! I SAID GIMME YOUR GODDAMN WALLET!{/i}" with vpunch
    "As his voice became more aggressive and loud. I panicked and started to cry out for help."
    i "{i}HELPPP SOMEONE! He--{/i}{nw}" with vpunch
    "The man immediately rushed towards me and pinned me to the wall muffling my moutn and pointing the knife only inches away from my neck."
    u "{i}SHUT UP YOU BITCH! HAND OVER THE DAMNNED WALLET!{/i}"
    i "{i}HHHMMMPPPPPP!{/i}"
    "As I tried to struggle and put up a fight. But seeing the knife going near and near my neck. All of my responses with this situation shut downs."
    "That is when..."
    u "{i}Ohhhh! You look cute, Miss. Kekeke! I'm going to have a little fun with you first.{/i}"
    "Taking advantage of the situation, the man started touching me down my thighs and moving closer to smell my hair."
    i "{i}HHMMPPP!...Hhm..hmm..hmm...{/i}"
    i "{i}'I feel sick... This is just really sickening...Help...Someone...Please...help me...'{/i}"
    "I really couldn't do much in this situation right now, all that I hope that this all ends swiftly, or for someone to save me."
    u "{i}HAHAHA! I wonder how long would you last before you complete break. AHAHA!{/i}"
    "Overpowering me and completely taking advantage of my body structure...He started to...do more than just than that..."
    "Slowly losing power and my sense of reality, the man shifted his attention from my thight to my chest as well as started licking the tears falling down on my cheeks."
    i "{i}Uhmmm....{/i}"
    u "{i}OH? Feeling good about all of this? I can't believe that you're a fucking slut dreaming of getting raped!{/i}"
    u "{i}AHAHA!{/i}" with vpunch
    i "{i}'I'm not a slut...My body...My mind...I can't...Please...anyone...{/i}"
    i "{i}'Just end it all...'{/i}"
    "That's when...everything shattered..."
    "I lost everything right on that night. My virgininty, my dignity, my reputation...{w}and lastly the people that I could trust."
    "The man that did that horrible crime wasn't put to justice nor even arrested. He just...vanished without any trace."
    "Due to my bad eyesight and it happened on a dark area, I wasn't able to draw or describe his face to the authorities."
    "It was not long when people spread rumor about that night."
    "I'm thankful that our school principal took action for not letting these rumors spread throughout the student body."
    "However, the damange was already done. I was relieved from my position as the student council president."
    "Alice, who was the council's secretary at that time filled in the missing position."
    "My family ignored me and told me that it was my fault for staying out late at night."
    "My so called friends spread rumors about me having multiple adult partners and sleeping with them in exchange for money."
    "The whole world shut me down and I have no toerh people to rely on..."

    with wipeleft_scene

    i "As days goes by and my reputation started to completely plummet, I let things be and tried to end all of my sufferring."
    i "I tried overdose, cutting myself as well as hanging. None seems to work and I believe this is my punishment."
    i "To keep on living with shame..."
    i "That's when you came into my life."
    i "On the day you offered your help without looking down at me and uniquely just want to help me out without any form of exchange."
    i "This person ignited something that was once extinguished."
    i "And now, you are infront of me. Listening to my story of how you saved me from everything."
    "As Iris summariezed and told me her deepest secrets, she rest her head on my shoulders."
    "I didn't know that Iris was going through a lot of pain and suffering. Who could've thought?"
    "Trying to process all of the information, I gently stroke her hair."
    mc "Iris... I wish I was there to helped you out. I could've saved you."
    "Without saying any word, Iris shook her head. Despite being sad, she now looks very calm and relaxed."
    i "You never dwelled or asked for my past. And yet you treated me with respect and helped me along the way."
    i "Thank you, [player]. And, I love you. Would you still accept someone as broken as me?"
    "And before I could even reply to Iris. She moved closer to my face and started to kiss me directly..."
    i "*chup* Ahh~"
    "Surprised on what is actually going on, I couldn't do much but to go on with Iris's flow."
    "I don't dislike Iris, but I'm not actually ready yet to be her lover. Especially she's currently undergoing this very traumatic event on her life."
    i "*chup...chup...chup...*"
    "From kissing, we transitioned to using our tongues and making sure that we gently feel each other."
    i "[player]~ ahn~ I love you so much~"
    mc "Iris..."
    i "*chup...chup...ahn~...*"
    "As our lips, mouth and tongue continues to dance. I lifted Iris and let her sit on my lap. And from there, I continued caressing her arms, shoulders and back."
    i "Ahh~...[player]~ You're a bit too bold, don't you think? Hehe~"
    "I completely ignored what Iris is saying and continue on kissing her and exploring the wholeness of her mouth."
    "With Iris stradding me, I couldn't help but to feel her head as well as her small body figure."
    i "*chup...lick...slurp...Ahn~*"
    i "[player]~ Please...love me, please...*chup...ahhn~*"
    i "I want to be only yours~ Exclusively yours~"
    "I didn't know that the silent Iris is something wild when it comes to intimate moments like these."
    "I continued to work my way and make sure that Iris is getting all the attention she wants. From her arms, I move my hands slowly around her sides down to her hips."
    "And despite her small and slender frame, I can feel the curves around her body underneath her clothes."
    i "AHHN!~ [player]~ That's my weakest spots...{w} Please...don't tease me there..."
    mc "Here?"
    "As I gently slid my hands insie her clothes from below. Iris lets out a very lustrous moan."
    i "Ahhhnnnn!~ Please...not the-- Ahhhnn~"
    i "[player]...Pwease...You're making m--ah~...e lose my min--AHHnnnnn~"
    "As I continue assaulting Iris with my kisses. Her body temperature starts to increase, I believe that she's already turned on."
    "Iris pulls away from the kiss and I did the same as we both need time to catch our breaths"
    i "Hey... How long are you just going to keep kissing me?..."
    i "It's not fun when you kept teasing me..."
    "Iris pouts as protest that she needed more than just a simple kiss."
    "As we took a quick breather, Iris stood up and kneeled on the floor completely starting at my member, ready to pop out to do some damage."
    i "Hehehe~ Looks like someone also can't wait~ May I?"
    "Iris slowly leans forward, inch by inch closer to my crotch. Using her lip, she carefully unzips my pants."
    "As my pants opens, my already erected member sprung up like a jack-in-a-box. Surprising Iris in the process."
    i "Wah! That surprised me!"
    i "Oh my...[player]~ Looks like you are not wearing anything underneath? Couldn't be that your underwear got wet when we ran through the rain?"
    i "Other than that... I didn't expect that you are hiding something large and girthy~ Hehe~"
    i "Well then..."
    "From kneeling down, Iris quickly stoods up and grabs hold of her pajamas."
    "Teasingly, she lifts up and pulls down the respective parts of her clothing. Showing her complete bare body."
    i "You're not the only one not wearing underneath~...Hehe~"
    i "Although this is embarassing...but for you and you only... You can look at me completely~"
    "Iris then completely strips off her pants and proceeds on straddling me again."
    "She then slowly and carefully undid the button of her top. And from here, I was able to see her full slender body and her beauty."
    i "[player]~ Please...take me...completely..."
    "A loss of words, Iris then grab ahold of my thick and erected member and slowly running against her pussy."
    "Sending shocks in our body like static. We both let out a moan showing out eagerness to be connected with each other."
    i "[player]~ Ahnnn~ I... I can't take it anymore!~"
    i "I'm going to put it in now... and I'm going to ride your sturdy hard cock using my stained wet pussy~"
    mc "Wait! Iri--!"
    "As I try to reason with Iris, she completely slides my cock right inside of her pussy. Taking the entire length on a single plunge."
    i "AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH~{w} Fu..ckkkk~ Ahnnnn~... So...big...God!"
    i "Ahnnn~ So fucking big...~"
    "My mind entered a blank euphoric state. All reason and understanding is temporarily disabled as I'm only focused on thing."
    "To fuck Iris hard as possible."
    i "I'm so sorry, [player]... I'm such a slut... I can't hold it in anymore...Ahh~"
    "As Iris slowly get comfortable with the possible, I went ahead and started slowly thursting my hips back and forth."
    i "Hiihhh!~ Fuck!...[player] I can't...Ahhh~ I can't anymor-- AHHHnnn~"
    i "I can't fucking believe it...Ahhhh~ I- Ahnnn~ I'm having sex wit--Ahhhnnn~ the one I love!"
    i "Ahhhnnn...God~ This is such a great feat! AHHHNNN~"
    "With each continuous thrusts, I can feel Iris's love juices leaking out of her pussy, making her drenched and slippery down there."
    i "[player]~ Ahhnnn~ Fuckkkk... God~ I just love you so much~ Iyaahhhnnn~"
    i "AHHnn~ [player]~...[player]~ I'm sorry if I'm such a slut right now...Ahhnnn~ Believe me...I cannot do thi-- Yahhhnnn~ to other people but only yo--AHHHH!"
    i "Please...Accept me~ AHHNNnnn!"
    mc "Iris...ughh... I-- Ahhnn~ I might..."
    "This is bad... If we keep up this pace. I am completely unprepared about all of this."
    i "Don't worry...Just cum inside me..! Ahhh~ I don't care...just do it~ Make me your cum dumpster~ Ahhnnn! Fill my hole with you--AHHHHnnN~ Cum!"
    "Iris began to quicken her pacing. She is completely ravaging her movements and completely pinning me to the sofa."
    i "[player]![player]~[player]... AhHNNN! YES! Don't fucking stop~ Keep on plowing your thick hard cock inside my slutty defiled pussy~ AHHH!"
    mc "Iris! GUHH! I'm going to....UGH!"
    i "Don't worry, [player]~ I'm going to cum as well~ Ahhnnn~ GOD FUCKING HELL! AHHNN~"
    i "Please, [player]~ Cum...CUM WITH ME PLEASE~ Shoot all of your load inside my fucking pussy! AHHNNNN!"
    i "AHHHNNnnnn~ Fucking GOODDDDD! [player]~{w}...[player]~{w} I'm gonn---{nw}"
    i "AHhhhHhhHhahhahhhhhHH~"
    "With every ounce of my strength. I shoot inside all of load inside of Iris without any second hesitation."
    "Her pussy kept on twitching as my cock continues to unload every last drop of cum I have in my system."
    "And exhausted, Iris passed out and drops on my chest."
    mc "Iris! Are you okay? Hey?"
    i "[player]?... hehehe~"
    i "I'm sorry...but I love you so much~"
    "Iris then kissed me and her strenght completely drains."
    "Right after Iris passed out, I carefully set her body on the sofa so that she'll be able to rest correctly without any worries."

    scene black with dissolve

    "A few moments later..."

    with wipeleft_scene

    "Short after losing conciousness, Iris slowly regain her strength and was able to wake up from her short slumber."
    i "Ugh...Where am I?"
    mc "You passed out about an hour ago, I think you pushed yourself too far."
    "I helped Iris to sit down straight and handed her a glass of water."
    i "Thank you, [player]. You're always so kind to me even though I forced you to have sex with me."
    mc "I don't mind about that, Iris. It's just that..."
    "I don't want to hurt Iris's feelings... but I know that rejecting her confession could lead her over the edge."
    "A very content Iris titled her head and waiting for my answer."
    mc "It's just it was a bit too sudden and things went by fast. And I'm also worried that you might be mistaken for your affection towards me."
    "And despite hearing those words. Iris still shows a content smile on her face."
    i "I know that you are worried, [player]. And I'm not rushing you about going on this relationship. Trust me, I can wait for you."
    "Showing not even a slightest hint of sadness or regret. I want to reassure her that I will always be the same [player] that she knows and love."
    mc "Iris...I...{nw}"
    i "I know!"
    "Cutting me off before I could speak out my thoughts. Iris's eyes perked up as if she has something in mind."
    i "How about you take me on a dinner date right after the first day of the Cultural Festival. That way we don't have to go far just to date."
    mc "That's actually a great idea, Iris."
    "Not gonna lie that is actually a really great idea as usually the night of the festival, couples around our campus confess with their chosen partner."
    "it's a small urban legend in our school, though. I'm inclined into believing such legend is plausible. But I do find it very romantic."
    i "And then, I'll be waiting for your reply until then."
    mc "Yeah"
    "As our conversation grew, we didn't noticed that the rain already stopped. Not only that, I'm already late and Seika might be worried sick about me."
    i "Oh! I must've taken much of your time tonight! I hope that Seika isn't made that you are home late."
    mc "I hope so. Last time I was late she didn't even talked to be for a day."
    i "That's terrible! Please, go ahead and prepare. Don't worry about me, I'll just rest for a while here."
    "Iris pushed me and asking me to pick up the pace. She knows that I'll be in much trouble if I stay here any longer."
    "With that, I immediately pick up my clothes from the laundry machine. I left the clothes lent to me by Iris and slide on my regular school uniform."
    i "See you tomorrow, [player]. I love you~"
    "I waved good bye to iris and I bolted out of her house and rushed towards my own which is just a couple of blocks away."

    with wipeleft_scene

label ch2_main_h:

    "As I manage to reach my house, I have noticed that the door is still lock, the lights are still turned off and I don't see Seika's shoes."
    "That's weird, it's already late and Seika isn't still home? Where could she be right now?"
    "Entering the house, I went ahead and plugged in my dead phone to the wall outlet near the kitchen."
    "My phone slowly boots up and I have noticed that Seika tried to call me more that six times."
    "Not only that, I also received six text messages along with six voicemails."
    mc "Crap, I knew it. She might be mad at me for not receiving her calls."
    "I immediately check the messages first."
    s "'Hey bro! Good news! We got the job and we are asked to start like immediately. Good thing we have no homework tonight! Hehe!'"
    "Oh yeah, I forgot the Seika left early to apply for the part time job. Odd though, they were asked to start immediately without training? I wonder how things will go."
    s "'Big bro? Are you home yet? Me and the girls are actually try fitting the costumes here. We'll have a short introduction later and brief training about serving customers. It's almost about to rain, I forgot my umbrella.'"
    "She was checking up on me the whole time. I told her to bring an umbrella everyday since it's already rainy season. What am I kidding? I also did forget mine."
    s "'Sup bro! We are just taking a short break after that brief training. It's already raining hard.'"
    "We'll I'm glad that she's currently working hard. And I hope she's not stuck there."
    s "'Bro! It's raining hard! I can't go home as well as my friends. We are going to stuck here for a while. Send help plz.'"
    "Well... Technically I was also stuck in the rain as well. So yeah, I can't help you out Seika. Sorry."
    s "'Good news bro! The manager told us that they'll pay us today extra just to work the extra hours while we wait for the rain. There's not much customers, just people sheltering from the rain."
    "Well... At least she's earning easy money during these times. I'm proud of her."
    "And lastly, checking on the last message she sent. To my surprise it's almost blank text but only with a capital I or small l. I can't really tell the difference."
    mc "Hmm... That's weird, maybe she left her phone unlocked inside her pocket? Who knows?"
    "Closing the messaging app, I tapped on the call voice mail history to check on the voice mail recordings." 
    "Most audio is around the time she was at work; I think she's just trying to reach me since I couldn't response to her text messages."
    "I went ahead and tap on the very first recorded message."
    "As I suspected, it'sjust a five second long recording just asking me to call her back. Checking on the timestamps, it connects well to her text messages."
    "Well... Since my phone literally died on me. I can't much do anything at that point."
    "Nothing much stands out in any of her recorded messages. As I was about to close the app, I remembered that one particular message she last sent that doesn't have a context."
    "As I scroll upwards to check the most recent voice mail recordings. I manage to find that is just minutes after her last message."
    "I opened that voice message and tried to listen to it."
    s "..."
    mc "That's weird, I couldn't hear a thing. Maybe the volume is too low?"
    "I adjusted the volume of my phone and tried to listen to the recording once again."
    s "..."
    mc "That's weird, I th-- {nw}"

    # sound effects jumpscare

    mc "AGHHH!" with vpunch
    mc "WHAT THE FUCK?!"
    "A loud piercing screech from the voice mail recording echoed througout the room for about good five seconds."
    mc "My ear! Ughhh... Is this Seika's prank for not answering her phone calls?"
    "Feeling annoyed, I immediately deleted the recordings as well as the other voice messages."
    mc "I should really comfront her about that recording."
    "As I turn to my left, I have noticed that it's already 10:15 in the evening and I still have no sign of Seika anywhere."
    mc "Where is that girl? She should be here by now..."
    "I turn to my phone once again and dialed her phone number. Hoping to hear her voice and to know where she is."
    "As I was about to hit the ring button, I suddenly hear a knock from our main door."

    # sound effects knock make sure it's surround version

    mc "Hmm? I think that's Seika. I'm coming!"
    
    with wipeleft_scene

    "I immediately ran towards the door and unlock the chain link, while the knocking continues."
    "I gently open the door..."
    "As expected, it was my little sister Seika. She looks drenched from the rain."
    "Her clothes, hair and bag are all socking wet. I'm also guessing the contents of her bag."
    mc "Seika! Why are you soaking wet? Did you ran into the rain?! Are you okay?"
    s "..."
    "Seika didn't say anything as she just lowered her head."
    "And without any words coming out from her mouth, she slowly walked inside the house. Leave a trail of water droplets on the floor."
    mc "AH! Seika! You're dripping all over the floor. Wait right there, I'll get you some towels to dry off."

    with wipeleft_scene

    "I rushed to the washroom and grab a fresh set of towel. I immediately ran back to Seika and made sure that she all dried up properly."

    with wipeleft_scene

    mc "Geez... I thought you leftwork right after the rain. Do you want to get sick, huh?"
    s "..."
    "Again, she didn't say any word. I cannot see her expressions properly as it is hidden underneath her bangs."
    mc "Hey...come on, Seika. Talk to me... I don't know if you are alright or something is wrong."
    s "..."
    s "I'm fine..."
    "She then shoved me out the way and dropped her school bag on the floor and proceed on going up the stairs up the her room."
    mc "Wait Seika!"
    "My call for her falls to closed ears. I guess she's not feeling well. I think she might've caught a cold."
    "As I try to chase after her, the door to her room closes and I can also hear the sound of the chain link."

    with wipeleft_scene

    "I couldn't do anything at this point. All I can do do is just stay in front of her door."
    mc "Hey...Seika. Are you okay?"
    mc "I know that you can hear me. So please, just here me out."
    "I know that there is something wrong and she won't even let me talk. But I want her to let me know."
    mc "If you are mad because I didn't pick up my phone earlier is because my phone battery died on me and I just charged it right after I got home."
    s "..."
    mc "I guess that you are mad because you waiting for me in the rain, hoping that I will come and pick you up. For that's worth, I'm really sorry Seika."
    s "..."
    mc "Please, just tell me if you're okay. And put some dry clothes. Don't forget to turn on your heater. I don't want you getting sick."
    "As I slowly left the front her Seika's room, I heard a faint crack on the floor coming from Seika's room."
    "I quickly turned around to see if Seika has opened the door to her room."
    "But alas, it was remained sealed shut. There is no point of pursuing her tonight, and besides she needs a proper rest now."
    "I then went ahead and entered my own room."

    with wipeleft_scene

    mc "*sigh*... It was a tiresomg day. I can't believe a lot of things happened in just a single day. I don't think my mind is ready for any of this."
    "Tired, I turned off the light on my room and locked my door. I wobbled to my bed as if it was sanctuary."
    "I then throw myself ignoring the fact that I am still wearing my uniform and rolled the blanket around my body."
    "I starred at my room's ceiling, thinking of all the things that happened today."
    mc "What a day...sigh...Not gonna lie, it's really been a stressful day for me."
    "As my thoughts slowly wanders to dreamland, I slowly remember what Iris and I done."
    mc "I can't believe that just happened. I really can't believe it."
    mc "I just had sex with one of the most popular girls in our school. Not only that, she also confessed her love to me. This is just too much to handle."
    mc "ARHG!"
    "Frantically, I just covered my face with my blanket. Hopefully I would just fall asleep."
    mc "..."
    mc "I hope that tomorrow Seika forgives me and just forget what happened today."
    "The sleepy goes to my eyes slowly and the cold darkness embraced me once again."

    with dissolve

call ch3_main_a

return
