label ch1_main_a:
    $ _history_list = []

    with wipeleft_scene

    "{i}The next day...{/i}"
    "As Seika and I finished our usual morning routine, it was time for us to leave for school."
    s "Big Brother!"
    s "Hurry up! We're gonna be late for school!"
    mc "Wait up, I'm still locking up the house! And mind you, we're earlier today."
    s "Hehehe~"
    "The warmth of the ever shining sun hits our skin; birds are chirping and the cool breeze passes by."
    "It's another bright and sunny day just like any other day, not that I mind though."
    "After locking the front door and making sure it's really locked, I caught up with Seika who was waiting for me on the sidewalk."
    "As we were about to walk to school, a familiar face greeted me."
    a "Ah! [player], good morning!"
    a "Are you heading to school now? {w}You don't mind if I tag along?"
    mc "Sure, I don't mind. It's nice to walk with friends."
    "Though why does it feel like as soon as I said that, the atmosphere became tense."
    "I quickly but subtly side-glanced Seika and I noticed her eyebrows furrowed together." 
    s "..."
    a "Hello Seika, how are you?"
    "As Alice noticed Seika, she slowly hid behind me, eyeing Alice somewhat menacingly."
    s "Fine... I guess?"
    "Though I dismissed the matter as Seika was just being shy."
    "It's kind of odd though. She rarely becomes shy around other people, but it's probably because we were all friends back in our childhood days."
    a "Well that's good to hear, it's been quite a while since we last talked to each other."
    mc "It's nice seeing you two still get along, even after many years."
    "Seika, Alice, and I go way back; even before we started junior high school."
    "We've been neighbors for the past 10 years. We used to go to the park and play, all three of us."
    "But then, Alice stopped coming over to play, and I always wondered why. From there, we all just slowly drift apart."
    "Until now, that is."
    "Nowadays, we see each other but we don't talk, not even small talk. We just pass by and go on about our day."
    "It made me think to myself, what changed?"
    "As we're walking together, I briefly remembered what happened yesterday about Alice."
    mc "Uhm...{w} Alice?"
    "I softly whisper to get her attention."
    a "Hmm?"
    mc "About yesterday, are you okay now?"
    "Her eyes widen, surprised that I recalled yesterday's events."
    "Honestly, she looked... touched; surprised yet happy that I'd even remember such an event."
    a "I'm okay now, no need to worry about me."
    "She smiles brightly, completely different from yesterday; an actual genuine smile. I wonder what changed or what happened?"
    "Despite whispering to Alice, Seika manages to overhear the conversation."
    s "What happened yesterday?"
    s "You told me that you were lazing around in your classroom."
    "Crap, I shouldn't have brought up this conversation."
    mc "I...{w} Uh..."
    s "Hmm?"
    "Seika stares menacingly at me, looking for answers."
    s "Hmmmmm?"
    "I don't think I can escape from this situation. I'm so screwed."
    mc "Well, you see..."
    s "Hmmm?"
    "I desperately looked around, my eyes evading Seika's unending glare."
    "Then my eyes laid upon a familiar figure, isn't that?!"
    mc "Wait... Is that?"
    "Noticing me from a short distance, she waves her hand and quickly caught up to us."
    i "Good morning, [player]. Good morning to you too, Alice and{w}...?"
    mc "Oh!{w} This is my little sister, Seika."
    "I briefly introduced Seika to Iris even though Seika was hiding behind my back."
    i "Why hello there, Seika! Nice to meet you."
    s "..."
    s "...Likewise."
    "Seika quickly returned to glaring at me before dismissing the matter."
    "Looking at it right now, the party has gained a few more people."
    "Glancing at my watch, I realized time passed a bit too quickly. We really need to get to school, otherwise we'll be late."
    mc "Anyway, I think we should start walking again. We still need to get to school."
    s "I agree, I don't like being late."
    a "Well then, let's be off now."
    "Alice, Seika, Iris and I started to walk starting from our neighborhood to our school."
    "This feels weird and different. It's my first time walking with two different people aside Seika."

    with wipeleft_scene

    "It felt like forever before we manage to reach our destination."
    "Even though it was just a 5-15 minute walk, it feels like a good hour."
    "No one is talking with each other and there is this cold and heavy atmosphere between them."
    "But after reaching the school lockers, we just waved at each other and head to our different room. And wait for class to start."

label ch1_main_b:

    with wipeleft_scene

    t "Alright, that's only the lesson for today."
    t "Dismissal is quite early today, but still don't stay at school for too long."
    t "Student with club activities be sure to return the keys to the faculty office before 5pm or before leaving the school's premises."
    t "That is all, thank you."
    "And thus marks the end of our school session for today."
    "It felt like forever that my back started to hurt from sitting all day."
    "Good thing that we were dismissed two hours earlier than the usual."
    mc "*Yawn*"
    mc "Finally!"
    mc "I got some time to kill today."
    mc "I wonder what should I do today, since it's a bit too early to go home."
    "Now that I realized it..."
    "I got more time to help the girls today."
    mc "Maybe I should check on Seika first to make up what happened yesterday."
    "As I slowly pack up my stuff, someone lightly tapped me on the shoulder."
    u "Hey..."
    "Turning my head slowly to know who tapped my shoulder."
    "I didn't expect that a finger was there to poke my check as I turned."
    u "Gotcha!"
    "Speak of the Devil."
    mc "Perfect Timing! {w}Hi there Seika"
    s "Hehehe~"
    s "Class ended early today!"
    s "Can you help me with *our* club today?"
    mc "As the matter of fact, I was actually headed to your classroom because I was going to look for you."
    s "Really?!"
    "Seika seems suprised to know that I was actually going to her classroom. Maybe she's expecting it?"
    mc "You looked surprised."
    s "*blush*"
    s "I-{w}I-{w}I'm not! {w}Stupid!"
    mc "Hehehe~ You're cute, when you blush like that."
    "I complimented on Seika as I pat her head."
    mc "Come on, show me the club room."
    s "Oh!{w} Uh..."
    s "S-{w}sure! Follow me."


    with wipeleft_scene

    "Me and Seika head outside the school building and head around the school yard."
    "This is an area located near the track and field."
    "Since there was no actual Softball Club before, me and Seika has to start from nothing."
    "Meaning we need to get at least 3 more members to be a fully fledged club and submit paperwork to get some funding from the school."
    "But for now, we have to use whatever resources we have as of now."
    "One thing for sure, Seika manages to snag a club room."
    mc "I'm still impressed that you managed to acquire a room even withou five members."
    mc "How did you managed to pull that off?"
    s "Well..."
    s "The thing is..."
    "I feel like something is a bit off due to the tone of Seika's voice."

    with wipeleft_scene

    "My eyes are probably going bad since I've been reading in the dim lights."
    "Or the actual club room is just an old ragged garden tool shed."
    mc "..."
    s "Ta-{w}dah?"
    "Seika tries to diffuse the situation with her clumsy cuteness acting."
    "But it doesn't work on this situation, sadly."
    s "Okay..."
    s "I know it's just a shed. But it's still something than nothing, okay!"
    s "And plus, I did it all on my own."
    "I have a mixed feeling of proud and confusion and also a hint of laugther."
    "Nonetheless, she did this all herself and I really proud of her because of that."
    mc "Seika..."
    "Seika faces me a looks me in the eye."
    mc "You did a great job, I am truly proud of you."
    "I gave Seika a warm smile and she eyes widens and started to tear up a bit."
    "She gave me a big smile and suddenly hugs me."
    s "I love you so much, big brother!"
    mc "I know, I know."
    mc "Come on, show me the inside of the clubroom."
    "Seika broke the hug and pulled out the shed's key on her skirt pocket."
    "And with that, she opened the shed's door using the key she got from the Faculty Office."

    with wipeleft_scene

    s "Welcome to the Softball Club!"
    "Seika energetically shouted and raises her hand to the air, catching some cobwebs in the process."
    s "Eww...{w} Cobwebs..."
    mc "Looks like we have to do some cleaning for a while."
    "Judging from the looks of it, it would take a good hour or so just to clean the entirety of this shed."
    "Afterall, this place hasn't been used in years and I can see a lot of trash all around."

    with wipeleft_scene

    "Armed with broom and couple of towel, and sheer determination."
    "We started our crusade on cleaning the clubroom."

    with wipeleft_scene

    "A few moments later"
    mc "And we are done! Great work today Seika."
    mc "This wouldn't be possible without your effort."
    "I said as I slowly slide the shelves back into their orignal positions."
    "Took a bit of time since some of the shelves are broken that I have to them completely out of the Clubroom."
    "Also, I have to take out the trash and separate them in the proper disposal areas."
    "That being said, I never heard anything from Seika right after I finishing my share of duties."
    "Feeling a bit worried, I called out her name."
    mc "Seika?{w} Where are you-"
    "And before I can finish my sentence. I found Seika near the shed's entrance. Crying and sobbing."
    "I immediately ran towards her. I don't know if something bad happened to her."
    mc "Hey Seika, are you okay?"
    mc "Are you hurt?{w} What happened?"
    "She didn't say any word and she just shook her head in response to a no."
    mc "Hey... tell me what happened so that I can help you out."
    "Without any words, she jumped into me and hugged ever so tightly. Tears immediately burst."
    s "BROTHER!"
    s "WHHHAAAA!"
    s "I'M SO SORRY!"
    s "*sniff* *sniff* *Uwaaaahh!*"
    mc "Hey... it's okay..."
    mc "Come on, tell me what's wrong."
    "I stroke her hair to help her calm down and to reassure her that everything is going to be okay."
    s "*sniffs* I can't {w} *sniff*"
    s "Find it anywhere {w}*sobs*"
    mc "What is it that you can't find exactly? I'll help you look for it."
    "Crying her eyes out, I can't make any word on what she is saying."
    "And then I noticed on her left hand, inside was a broken necklace chain."
    "I immediately understand what is the thing she cannot find."
    "It was a Heart-shaped pendant"
    "I gave Seika that pendant after winning the championship 2 years ago."
    "A lot really happened back then, she kept on fighting on the championship even after injuring herself in game."
    "And as for a reward, I gave her that pendant that I saved up using some of my own allowance."
    "At first, I thought she wouldn't like it because it's a necklace. And she refuses to wear any types of accessories as it hinders her movements."
    "But this was a complete exception, she loved it and I never actually saw her remove it or even lost it."
    "Until only now..."
    mc "It's okay Seika"
    mc "I could just get you a new one..."
    mc "Don't worry about it."
    "Still not letting me go or show any signs of her tears lighten up. All I can do is just comfort her. Just for a bit."
    "A few minutes had past, Seika is still crying over the missing pendant. I have to do something."
    "And without moving her, I decided to look left and right just to spot any items that are laying down on the floor."
    "But there is no luck inside the shed."
    mc "*sigh*"
    "I let out a small sigh, decided to gaze on the entrance side of the shed."
    "If I'm correct, it should be still inside since while cleaning Seika didn't stepped out."
    "Upon realizing, didn't Seika got caught up with some cobwebs earlier as she entered the shed."
    "Maybe during her clean up, she manages to break the necklace."
    "And on analyzing near the entrance, I was correct."
    mc "Seika, look!"
    "Lightly tapping Seika's head to get her attention."
    mc "I think I found the pendant, check over there by the door frame."
    "Fixing herself as she stoop up, Seika immediately head to the shed entrance."
    "She kneels down quickly and grabs the pendent and pressed it against on her chest."
    "Holding back her cries, she turns to me and gave me a teary smile of joy."
    s "Thank you, big brother."
    "Seika finally calms down and returned back to her normal state after a few moments."
    mc "Are you okay now?"
    s "Yeah, {w}I'm okay now. Thank you."
    mc "Still..."
    mc "The necklace on that pendant is badly broken, but still it still fixable."
    mc "Mind giving it to me so I can fix it later at home?"
    s "Sure thing big brother."
    "Seika handed me her broken necklace and pendant. I quickly stored it on my bag so I won't lose it this time."
    mc "Anyways, I think we could call it a day now. Don't you think?"
    s "It's still a bit early, so I'll stay for a bit."
    s "There may even be some students that migh be interested to join in today."
    mc "Well, if it's okay with you then I'll go check around for a while."
    mc "I still have a few things to do right now."
    s "Like talking to those bitches?!{nw}"
    $ _history_list.pop()
    mc "Did you say something Seika?"
    s "Uh...{w}What?"
    mc "Uh...{w} Nevermind then."
    mc "I'll be gone for a bit. Wait for me at the shoe locker again, okay?"
    s "Okay! See you later, big brother!"

label ch1_main_c:

    with wipeleft_scene

    "I decided to take a little stroll around the school ground behind the main building."
    "The usual place for the Track and Field, and other stuff such as the garbage disposal areas."
    mc "Oh yeah"
    mc "Irisi siad that there's a garden behind the school building and she said that she might be there today."
    mc "Might as well check for her there."

    with wipeleft_scene

    "Walking for a bit, I was able to reach the other garden that Iris mentioned yesterday."
    "And I was in awe"
    "This garden is much grander than the ones from the rooftop"
    "There's vegetation and flowers in rows. All in beautiful arrangements."
    i "[player]?"
    mc "Oh, hello Iris!"
    "As I waved back at her."
    mc "Anything I can help you with?"
    i "Ah yes!"
    i "Are you knowledgable in preparing grow beds for different plants?"
    mc "Just a little bit, I used to garden as well."
    i "That's great to hear!"
    i "Can you prep up the grow beds while I prepare the seedlings?"
    "Iris pointed at the vast garden that needed to be prepared."
    "Unlike the secret rooftop garden, this particular gargen is much bigger and covers a lot more space."
    "I wonder how did she even manage this all by herself."

    with wipeleft_scene

    "I took off my jacket so I can work without any hindrances."
    "This could really take a while as this is much a complicated task compare cleaning the Clubroom."
    i "Do you want to borrow some gloves?"
    mc "Yes please, thank you"

    with wipeleft_scene

    "Several minutes passed"
    "This is taking forever than I originally anticipated."
    "Looking at the garden, I'm still halfway done and it already took a good thirty minutes."
    "And beside thats, it's really awkward with this intense silence between me and Iris. As we are just sitting beside each other."
    "Trying to get some conversation going, I tried to glace over at Iris."
    "She seems occupied, and clearly enhoying her work right now."
    mc "Uh...{w} Iris?"
    "No response as she's really occupied with her work."
    "I shrugged it off and dismissed the supposed interactions. I'll just focus on my work."
    "..."
    "It's really awkward right now and the atmosphere is bit heavy."
    b2 "Uh, Iris?\n\n Uh...[player]"
    "It was a surprised that we both glance and spoke at that same time."
    "It felt like time slowed bown for a bit as out eyes meet each other."
    mc "Uhh... You first, Iris"
    i "Ah! {w} I see..."
    i "Well...{w}Are you enjoying yourself?"
    mc "Yes! I am enjoying working beside you."
    mc "I mean...I am enjoying working the garden with you."
    "Crap, I just weirded out Iris. That being said, I just let out a long sigh."
    mc "*sigh*"
    mc "I'm sorry Iris. I got a little bit distracted because I was trying to have a conversation with you earlier."
    mc "I guess that I weirded you out, huh?"
    i "Oh no! I'm sorry as well"
    i "You see, when I'm doing my garden, my mind wanders off a bit."
    i "It's just I love gardening so much, it helps me escape this world."
    "Iris smiles sweetly and it makes my heart skips a beat."
    mc "I see"
    mc "If that is the case, I'm very much the same."
    mc "My mind tends to wander around when I'm cooking meals."
    i "Really? I didn't know that you cook."
    i "That's a very good trait and skill to possess."
    i "May I try some of your cooking sometime?"
    "Iris asked out of the blue."
    mc "I-{w}... Sure!{w} I'll prepare you a dish soon."
    "Iris once again showed me a very sweet smile."
    mc "Oh before I forget. I actually have a question though."
    i "Sure, what is it?"
    mc "I'm not prying or anything but, why did you suddenly moved to our neighborhood?"
    i "Oh that! There's actually no reason behind it."
    i "I just moved in because it was a bit cheap compare my old house."
    mc "Are you living by yourself then?"
    i "Actually, yes. I am currently living on my own."
    mc "Really? For how long now?"
    i "Oh...just a couple month ago."
    "So, she's been living alone and living indenpently already"
    mc "If I may, why live independently?"
    "After saying that, the mood suddenly shifted."
    i "Well..."
    i "The thing is..."
    i "Once you put on a spotlight like the top one pedestal, people are expection more from you."
    i "Being the president, top one student and preparing stuff for your future ca be really stressful."
    i "And I don't want people to be disappointed at me for not doing my best."
    i "It's just that..."
    "Her calm demeanor and cherry attitude slowly change as small tears trickling down her eyes."
    i "I'm just getting a bit tired, that's all."
    "I want to comfort her, but I ended up reachng my hand to her hand."
    mc "It's okay to be tired and just do your own stuff at your own pace."
    "I gave Iris a warm smile as she wipes her tears."
    i "Can I tell you something?"
    mc "Sure, I'm all ears."
    i "Well...{w} The real reason why I started gardening is to get away from my everyday burden."
    i "It's also the reason why I choose that neighborhood, since it's quiet and that specific house has a large garden."
    i "I want my own getaway from all of this street."
    i "After all..."
    i "...I have depression"
    "The world stopped as I learned that Iris, the kind, cheery and loving person is keep something dark inside of her."
    "Still holding her hand, I'm not going to let her fall..."
    mc "Iris, no matter what happens. Stay strong."
    mc "Do it for me and do it for yourself, okay?"
    mc "I promise to help you with everythhing I got."
    "Iris nodded to me while smiling as she slowly let go of my hand."
    i "I will do my best, after all I still have college examination as well."
    i "So, doing garding helps me stay focused."
    mc "Just promise me not to push yourself too hard, okay?"
    "We gazed into each other's eyes and Iris didn't say a word and just nooded."
    mc "How about we wrap things up now?"
    i "Yes, let's just finish this currently and then we can stop for the day."
    mc "Alright, let's do out best!"
    "And with that, me and Iris resumed our work."
    "But as we are able to get started again, I hear Iris grunted."
    i "Argh!"
    mc "Iris! Are you okay?!"
    "I immediately rushed towards Iris to check up on her. I noticed that she cut her hand with the trowel by accident."
    i "I'm fine don't worry. It's just a little cut."
    mc "Still though, we have to clean that fast."
    "I quickly reached for my pocket to get a clean handkerchief to at least stop the bleeding."
    i "It's okay, don't worry. It is very common to get cuts like these during gardening."
    i "I will go ahead and clean up okay?"
    i "I'll be right back, dont' worry."
    "Iris quickly stood up and heads for the nearest water faucet to get her hands clean and to clean her small cut."

    with wipeleft_scene

    "After a few minutes later, Iris returns from cleaning her wound."
    i "Hi there, I'm back."
    i "I'm really sorry that I got some blood on your handkerchief."
    mc "It's okay, but..."
    mc "It looks like we just have to resume this some other time."
    i "But I can still work."
    "Iris protested"
    mc "No, you need to get home and get some antiseptics for that wound."
    i "But..."
    "Iris is persistent, but I cannot allow her to work for today due to her open wound."
    mc "Look, I'll help out again tomorrow. Just head home for today and get that wound clean and fixed."
    i "Well...{w} Only if you promise to be at the rooftop garden tomorrow."
    mc "I promised. I'll grab all of your stuff and I'll walk you to the entrance."
    "I put on my coar and carried Iris' bag as I walk her to the school's main gate."

    with wipeleft_scene

    "I escorted Iris to the School's gate just to make sure that she is actually going home and not stay behind."
    "I stopped by the school main gate as I cannot escort Iris further as I have still work."
    mc "Okay, I wish that I could walk you home today. But I still have some work to do here in school."
    i "It's okay, I don't want to be a bother."
    i "In any case, I'll see you again tomorrow on the rooftop garden."
    mc "Yeah, I promise to be there."
    i "By the way, what about your handketchief?"
    "Iris handed me the bloody handkerchief but she quickly withdraw her hand again."
    i "On second thought, let me clean this up for you."
    i "I don't want to return this to you currently on this state."
    mc "Oh, it's fine. You can keep it if you want to."
    i "Is it really okay for you?"
    mc "Yeah sure, go on ahead."
    mc "Just clean it first thought, you can't actually use it for now as it has some blood on it."
    "I joke around as Iris stored my handkerchief to her bag."
    i "In any case, thank you for today again. I'm glad that I was able to talk with you."
    mc "Don't mention it, I'll help again tomorrow."
    i "I'll be going now, bye~"
    "Iris heads home as I wavy my hand to say Good bye."
    "With that being said, I went ahead and look for Alice as I know she's already have a lot on her plate."

label ch1_main_d:

    with wipeleft_scene

    "As I head back to the school's main building. Noticed that Alice is struggling just to carry some documents."
    "I rushed towards to Alice and call out her name."
    mc "Alice!"
    "I shouted to get her attention. But it seems that it went over her head."
    "I immediately ran up to her to help her carry the pile of documents."
    a "[player]? Is that you?"
    a "Sorry I didn't noticed you. I was a bit occupied with these recent compilation of documents."
    mc "It's okay, let me help you carry all of that."
    "As Alice handed me the documents. And for a brief moments, our hands touch and I know that something isn't right."
    mc "What the...?"
    "Without any second thoughts, I dropped all of documents and reached my hands to Alice's forehead."
    mc "As I suspected. Alice, you're burning hot."
    a "No...{w} I'm fine...I'm just a bit-{nw}"
    "Right before she can ever finish her sentence. Her weakened body slowly lost all of it's strength and collapse on me."
    "Alice passed out due to fever and extreme exhaustion."

    with wipeleft_scene

    "Without wasting anymore time, I quickly carry her into my arms and rush her to the school's infirmary."

    with wipeleft_scene

    "Glady, the school nurse is still for the day and I was able to get Alice there right on time."
    "The school nurse was able to check on Alice. She checked on her temperature and she's currently have a minor fever."
    "Still unconciouse, we lay Alice on a vacant infirmary bed to let her body rest for a bit."
    "The nurse assured me that there is nothing to worry about as Alice simply passed out due to exhaustion and fever. With enough rest, she'll be able to walk later."
    "I slide a chair near the bed where Alice is laying down."
    "I'm worried about her and I know that she's keeping something all to herself."
    mc "Alice..."
    mc "What on Earth are you doing to yourself..."
    "I bust out my phone to text Seika not to wait for me and just head straight home after her duties."
    mc "And there, sent. Hopefully that Seika reads my chats."
    "I slid back my phone to my pocket and patiently wait for Alice to wake up from her rest."
    "..."
    "As I wait for Alice, I didn't know that I will get sleepy."

    with wipeleft_scene

    "A few moments later..."
    u "...ey..."
    u "..hey..."
    u "Wake up..."
    u "[player], wake up..."
    "With gentle nudges, I was able to wake up from own rest."
    u "Hey...{w} Are you okay?"
    "Opening my eyes, I was greeted by a now awaken Alice from her short slumber."
    a "[player], are you okay now?"
    mc "Sorry Alice, I must've dozed off while watching over you."
    "I didn't noticed that I've fallen asleep while waiting for Alice to wake up from her rest."
    "It felt like a good hour or so that the sun is already a hue of orange and red."
    a "Hmm... It's okay,{w} it's my fault for suddenly collapsing."
    "Alice smiles but the same as last time, it was hollowed and sad."
    "I really don't want to pry on this but she leave me no choice as I worry about her as a friend."
    mc "Alice,{w} why are you doing all of these?"
    mc "Like, I really don't know what is your current situatin or anything."
    mc "And I'm sorry but I am really worried about you."
    "I said to her while mustering all of my courage just to know the truth."
    a "I'm sorry..."
    a "I am just too weak and I don't want to let them all down."
    a "I know that I am not doing my job properly..."
    "Just as she's about to burst into crying, I reached out my hand and gave her a comforting stroke on her hair."
    mc "I really don't know how to comfort you or anything."
    mc "But I just want you to know that I'm always here for you and give you a helping hand."
    "I really want to know more about her currenty situation but I think this isn't the right time for that."
    a "What you are doing right now is already more than enough to comfort me and to know that you'll always be by my side."
    a "Thank you for caring me."
    "With teary eyes, once again she gave me a smile. Different and it has more life into it."
    mc "I should get the nurse to check up on you, wait for me a bit."
    "As I try to stand up from sitting, Alice pulls my sleev and stopped me from going anywhere."
    mc "What is it Alice? Is there something the matter?"
    "With a sudden shift of atmosphere, the tone of her voice suddenly change."
    a "I trust you, [player]. And I just want something to get off my chest for a while now."
    "Alice lets go of my sleeve and I went back sitting on the chair just to listen what Alice is about to say."
    mc "Okay Alice. I'm all ears now."
    "Alice took a huge deep breath as if she's mustering all of her thoughts into on paragraph."
    "And with a serious look in her eyes, she starts..."
    a "True that I've been neglecting myself for a while now and I've been literally out of my regular self."
    a "But, it's just I don't want people to be diappointed at me. Ever again..."
    a "Being the Student Council president, staying at the top of every class, responsibilities and such."
    a "People are expecting me to do many things"
    a "But I'm..."
    a "I'm just a normal person..."
    a "I do get tired, sad, mad and even feel nothing at all."
    a "And I know that some people are expecting me to fall down."
    a "But..."
    a "I really don't know what to do..."
    "Holding back her tears, she cluthes on the bedsheet as she slowly leans to lower her head."
    "She's been holding that for how long now?"
    "Fighthing alone and doing this all by herself, she can't escape the high expectations that people put her on the pedestal."
    a "*sobs* {w}I just..."
    "Without any second thoughts, I press her head against my chest and gave her a caring embrace."
    mc "I told you before, {w}if you ever need someone to talk to. I'll be there for you."
    mc "You don't have to fight all of these struggles all alone, you got someone that got your back all the time."
    "And with that, Alice started to cry her heart out."
    "She's been carrying this huge burden on her back all these time."
    "And she barely managing all of it on her own."
    "I gave a few moments locked into my tight embrace while she slowly calms down and breaks free from me."
    mc "Are ou feeling a bit better now?"
    a "Yeah, I actually feel a lot better now. All thanks to you."
    a "This is the secnond time that I cried in your arms and I feel comfort doing that."
    "Alice smiles as she stated that."
    "It actually made my heart skip a beat for a second."
    mc "Well anyways, I should get the nurse now to have you checked."
    "Alice nodded as I went outside to see the nurse."

    with wipeleft_scene

    n "Okay Miss Alice, you are not allowed to work for good couple of days."
    n "And I'm giving you some medicine for the night so you don't have to worry about a thing."
    "As the nurse handed Alice a small paperbag with 2 tablet medicines."
    n "Anyways, Mr.[player]. Make sure that Alice gets home safely."
    mc "Will do"
    "We are both dismissed by the Nurse."

    with wipeleft_scene

    "Almost taking forever, alice and I manage to arrive at the doorstep of her house."
    "It was a long, awkward walk between us two. There is nothing but pure silence and Alice staggering to walk straight."
    mc "Okay, we're here not Alice."
    a "Thank you, I can take it from here now."
    mc "Do you want me to come inside as well? Just to check if you're really going to rest."
    a "It's okay, don't worry. {w}I'll go to rest after changing my clothes and getting some dinner."
    mc "Okay then."
    "I handed over Alice's bag to her."
    mc "Also, I will do your paperworks tonight. Just to make sure."
    a "You really thought of it up to this point, huh?"
    mc "What can I say? I'm just worried that's all."
    a "Okay, I better get going inside now."
    a "Thank you so much for today. I really can't thank you enough."
    mc "Don't mention it, I'm always glad to help out."
    "Waving her goodbye, Alice opens up her door and walks inside."
    mc "Guess that's today, huh?"
    "I turned around and head towards home."
    "*crash*"
    mc "What was that?"
    "Looking left and right, I thought that I have heard something breaking."
    "I let out a long sigh and dismissed the matter."
    mc "It's just probably my imagination."

label ch1_main_e:

    with wipeleft_scene

    "As I head home, I noticed that the lights are still off despite it's almost night."
    "I gently opened the door and called out Seika."
    mc "Seika, I'm home!"
    "There is no response and I think that Seika is still not home yet."
    "I quickly check phone if there are any messages coming from Seika."
    mc "Oh! I got a message from Seika."
    s " 'I'll be home a bit later! I got 4 new members to join our Softball Club today and we are just out celebrating.' "
    mc "How did she even manage to get four members on the first day?!"
    mc "Well anyways, I should start doing all of stuff."
    "I sent a reply to Seika saying that I'm already home and I'll be waiting for her to come home."
    "And without changing my clothes, I head to the living room and started working on fixing Seika's necklace and Alice's paperworks."

    with wipeleft_scene

    "It took several hours to tinkier on Seika's necklace and finishing all of Alice's paperworks."
    "Time passes by fast that I didn't noticed that I slowly fallen asleep after working."
    "..."
    "Several hours later"
    mc "*Yawn*"
    mc "It looks like that I've fallen asleep right after working."
    "And as I try to get up, I noticed that I have a blanket laid on my chest."
    "This wasn't here before, but at least I was able to finish all of my work before I dozed off."
    "And as I lean back on the couch."
    "I felt that someone is laying behind me."
    "As I turn around, I noticed that Seika is sleeping soundly on the couch."
    "She must've arrived late but was able to give me a blanket while I was sleeping."
    "I stood up from where I'm stting and reached out my hand to stroke her hair."
    mc "You did a great job today Seika."
    mc "And from the looks of things, I have to carry you back to your room."
    "Slwly and carefully, I carry Seika into my arms and I climbed up to the second floor of our house."
    "Right outside the door of her room, I have noticed that her room is completely sealed off and is locked from the inside."
    mc "That's ood, Seika probably locks her room every now and then."
    "It's pretty much understandable as she is clearly on that age now."
    "I don't wanna wake up Seika right now as she is clearly sleeping soundly."
    "Since I don't have any other options, I decided to head to m room and we'll just share the same bed. It is spacious anyways."
    "I think it's fine for her to sleep on her uniform, but I have to make sure that she doesn't feel cold."
    "I lay her on my bed and cover her with my blanket."
    "Dimming the lights, I slowly slide inside the sheets with her."
    "It's been a long time since Seika and I shared beds or even get this entirely close."
    "Covered in darkness, I turned my face to see Seika's face."
    "She is both beautiful and tired, I really wonder how she manage to get the new members to join her club."
    "I really can't describe it, but I just want her to be more like this."
    "She's slowly growing mature but I still want her to be my very reliant little sister."
    "That make me love her a lot and It's my duty to keep her happy."
    "As thoughts slowly fills my head, drowsiness tooks over and pulls me straight to dream land once again."

call ch2_main_a

return
